{%set name = "wtforms-appengine" %}
{%set camelName = "WTForms-Appengine" %}
{%set version = "0.1" %}
{%set hash_type = "sha256" %}
{%set hash_val = "56824d785458a8da68fab3d3ba3561831115965197a85a624e4bb9534c69fe19" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ camelName }}-{{ version }}.zip
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - wtforms >=1.0.5

  run:
    - python
    - wtforms >=1.0.5

test:
  imports:
    - wtforms_appengine

about:
  home: http://github.com/wtforms/wtforms-appengine/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Appengine tools for WTForms'

extra:
  recipe-maintainers:
    - pmlandwehr
