travis:
  secure:
    BINSTAR_TOKEN: WFUR4Z/WtvVe4kx5LvDGeTvoQVp+ix6G0jEb8R07H804oV0bjnF4DYhCk+mJQVN93Dh78W0TwAQCM0oTcUzNFjKWP0KKFYmM8EKLSIoihDgmUNhqbBXu5RIFFQDnPq/qfpNGsUIMzBq4sneVL9r31obVttlitRMLvgLGPwa2gN8bh0XD//BhWM1IFSgYT0J0DHE29RS0G0G7dbNYgTdmR/O9L83u7aa9R08u4iI1SYkoc45H6RAWEsCEDrrpupPzNd4D9iNJvHlsneetUi+Yna7SCpvywddyw7pjTiDIzbGF+4vlaL2R9eGAjD6/k2xE8kxUYcCNXj0L29Fj/VpQDveMpDQTgfVeikHV406Ng2QqfHwP2hQtjmCKE8IR6Ywn4xKFTKLBgW7zaMGhDcH1tF/J92f1ppp/CszqX+CLnU9FPyXOj0zuSqH/OUs6icu8nkriEWy1TwsMiSR1Rz8Y7ItuIgHynD9kUOEq+Rv59eFzUGpnsbAsib6CLlJucz0Qx9pSKkoVOLPXMNPFcpt9FZKWFzSYRK8675GDZBLJ87Zg9A+Y07n6sAMESB5BC7pJd0y3IAFur8NHR+bSlDGvjd3eL8l3S013AMTipc4Oz5KUFjGm3NAkZLCwGimqCSNAPPLiELJgfBWotqZqoimdfloVJkB+3OY+HBJbYkQtMkU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
