travis:
  secure:
    BINSTAR_TOKEN: m8X/wBFydU+DyCvosIJr4loajQykwXX5e3r9X/RWo+Qn8VvrQGTSILEYywYaLPqY9rytgpHbgKeuwvjThZ8vMR2/TYUvaGT5Z3bs/XfYlxvucxtfjDXnP7VHATi74M4f2TIM1hAIRpViCr4QwKGmwxYM+NuwguCkws4Nfp3tNto+mXZLhIh3SQSKahwMTsQtDUQRd/sxxv0yyTEp8MP5gVzZr9ukYPwmW44y0emE2UnR3pNsomNdnTgItiVM8cmaPbWrxVve/XLzYwh8+WcNc+3R4+lYG/CzMyjmznoTH7luHTNC27tXApoeejtEP3ov++AVesoDoxwhaC9ao3iPsStYL2KvLnuv7Ts/g1p1Hr8EisBYogjyyzH2Y8CVN3I1q0vvVHLyUe8ntM8VFssa92k3YgkNKkN61cFglOY517+jH7z47HeqGoxFh2e761ox6WK9dC+0kwATrpBmZ0ZehrtfXBdPOqmsjUawhMCwSls08J+gMXpPUawAnh7/aTQPpGwagg6I220zrzy7FkAVukfEjOKIzTTo6x8kd8oRJ8NBVdHuVDQDx4S3erO9W2kQOiIhio+0Q8Nkreu9jaV8ufXd3leckaGFL2W0F1FlaVBOC+F1jamRhDGlk3b1iMhtkTRw/bB9LwBlqS2eVXUSHnD6E29Unca2vGiYNqiB3DA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
